In [2]:
import numpy as np
import torch

# Numpy Review

### 1D Array with Numpy

In [3]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [4]:
print('Rank of t: ', t.ndim)       # 차원
print('Shape of t: ', t.shape)     # 행.열

Rank of t:  1
Shape of t:  (7,)


In [5]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1])    # Slicing
print('t[:2] t[3:] = ', t[:2], t[3:])          # Slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


 ### 2D Array with Numpy

In [7]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [9]:
print('Rank of t: ', t.ndim)       # 차원
print('Shape of t: ', t.shape)     # 행.열

Rank of t:  2
Shape of t:  (4, 3)


# Pytorch Tensor

### 1D Array with Pytorch

In [10]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])  # float형 tensor 생성
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [13]:
print(t.dim())    # rank
print(t.shape)    # shape
print(t.size())   # shape
print(t[0], t[1], t[-1])    # Elemant
print(t[2:5], t[4:-1])      # Slicing
print(t[:2], t[3:])         # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D Array with Pytorch

In [14]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [15]:
print(t.dim())   # rank
print(t.size())  # shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


# Broadcasting

In [17]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [18]:
# Vector + Scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [19]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


# Multiplication vs Matrix Multiplication

In [24]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))


-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


# Mean

In [26]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [28]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [30]:
t = torch.FloatTensor([[1, 2], [3, 4]]) # 2 x 2
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [31]:
print(t.mean())
print(t.mean(dim = 0))  # 1 x 2
print(t.mean(dim = 1))  # 2 x 1
print(t.mean(dim = -1)) # == dim 1

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


# Sum

In [33]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [34]:
print(t.sum())
print(t.sum(dim = 0))  # 1 x 2
print(t.sum(dim = 1))  # 2 x 1
print(t.sum(dim = -1)) # == dim 1

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


# Max and Argmax

In [35]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [37]:
print(t.max()) # Returns one value: max

tensor(4.)


In [39]:
print(t.max(dim = 0)) # Returns two values: max and argmax
print('Max: ', t.max(dim = 0)[0])
print('Argmax: ', t.max(dim = 0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [41]:
print(t.max(dim = 1))
print(t.max(dim = -1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


# View (Reshape)
* 기본적으로 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지되어야 한다.
* 파이토치의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추한다.

In [42]:
t = np.array([[[0, 1, 2],
             [3, 4, 5]],
            [[6, 7, 8],
            [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [43]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [44]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


# Squeeze
* 해당 dimension의 element 개수가 1인 경우에 그 dimension을 없애준다.

In [45]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [46]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [47]:
print(ft.squeeze(dim = 0)) # 3 x 1
print(ft.squeeze(dim = 1)) # 3

tensor([[0.],
        [1.],
        [2.]])
tensor([0., 1., 2.])


# Unsqueeze
* 해당 dimension의 element 개수가 0이면 그 dimension을 1로 만든다.

In [48]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [49]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape) # 1 x 3

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [50]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [51]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape) # 3 x 1

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [52]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


# Type Casting

In [53]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [54]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [55]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [56]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


# Concatenate

In [57]:
x = torch.FloatTensor([[1, 2], [3, 4]]) # 2 x 2
y = torch.FloatTensor([[5, 6], [7, 8]]) # 2 x 2

In [58]:
print(torch.cat([x, y], dim = 0)) # 첫 번째 차원을 늘려라 => 4 x 2
print(torch.cat([x, y], dim = 1)) # 두 번째 차원을 늘려라 => 2 x 4

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


# Stacking

In [59]:
x = torch.FloatTensor([1, 4]) # 2
y = torch.FloatTensor([2, 5]) # 2
z = torch.FloatTensor([3, 6]) # 2

In [60]:
print(torch.stack([x, y, z])) # 3 x 2
print(torch.stack([x, y, z], dim = 1)) # 2 x 3

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [61]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0))
                   # 1 x 2         # 1 x 2         # 1 x 2       => # 3 x 2 

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


# Ones and Zeros

In [62]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]]) # 2 x 3
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [64]:
print(torch.ones_like(x))   # x와 똑같은 shape인 1로 가득찬 tensor
print(torch.zeros_like(x))  # x와 똑같은 shape인 0으로가득찬 tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


# In-place Operation

In [67]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [68]:
print(x.mul(2.))  # x * 2 (일시적.)
print(x)
print(x.mul_(2.)) # 기존 tensor에 덮어쓰기 !! (_를 넣으면 !!)
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
