In [2]:
import numpy as np
x = np.array([1,3,5])
print(x.mean())

3.0


In [3]:
print(x.shape)

(3,)


In [4]:
a = np.array([[1,2,3],[2,3,4]])
print(a.shape)

(2, 3)


In [5]:
x = np.array([1,3,5,7,9,11]).reshape(3,2)
print(x)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [7]:
y = np.ones([3,4])
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
list1 = [[1,11],[2,12],[3,13]]
print(list1[1][1])

12


In [9]:
print(list1[:][1])

[2, 12]


In [10]:
print(list1[1])

[2, 12]


In [11]:
np_ary = np.array(list1)
print(np_ary)

[[ 1 11]
 [ 2 12]
 [ 3 13]]


In [13]:
print(np_ary[:,1])

[11 12 13]


In [15]:
import math

In [17]:
math.sqrt(2)

1.4142135623730951

In [18]:
math.sqrt([2,3,4])

TypeError: must be real number, not list

In [19]:
np.sqrt([2,3,4])

array([1.41421356, 1.73205081, 2.        ])

In [20]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [21]:
a[1,1]

6

In [22]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.zeros([2,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
ary = np.array([[1,2],[3,4]])
print(ary)
print(ary.transpose())

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [29]:
x = [1,2,3]
y = [4,5,6]
print(x+y)

[1, 2, 3, 4, 5, 6]


In [30]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y)

[5 7 9]


In [32]:
x = np.array([4,8,12])
y = np.array([2,4,6])
print(x / y)

[2. 2. 2.]


In [36]:
a = np.array([10,20,30,40,50,60,70])
b = a[1:6:2]
print('b:',b)
b[1] = 10
print('b:',b)
print('a:',a)

b: [20 40 60]
b: [20 10 60]
a: [10 20 30 10 50 60 70]


In [37]:
a = np.array([10,20,30,40,50,60,70])
b = np.array(a[1:6:2])
print('b:',b)
b[1] = 10
print('b:',b)
print('a:',a)

b: [20 40 60]
b: [20 10 60]
a: [10 20 30 40 50 60 70]


In [50]:
ary = np.random.random(5)
print(ary)
print(np.all(ary >= 0.3))
print(np.any(ary > 0.7))

[0.93131225 0.11142013 0.74930098 0.29607899 0.53084125]
False
True


In [53]:
h = np.array([173, 186, 171, 189, 179])
w = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = w / (h**2)*10000
bmi

array([21.85171573, 17.11180483, 21.75028214, 24.7473475 , 21.44127836])

In [54]:
print(np.array(bmi)>21)

[ True False  True  True  True]


In [59]:
np.linspace(1,31,5,retstep=True)

(array([ 1. ,  8.5, 16. , 23.5, 31. ]), 7.5)

In [61]:
np.linspace(0,12,3, endpoint=False)

array([0., 4., 8.])